version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
    ports: ["5432:5432"]
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  jaeger:
    image: jaegertracing/all-in-one:1.57
    ports:
      - "16686:16686"   # UI
      - "4318:4318"     # OTLP http

  backend:
    build: ./backend
    environment:
      PORT: 3000
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: todo_app
      OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4318
    ports: ["3000:3000"]
    depends_on: [db, jaeger]

  frontend:
    image: nginx:1.27
    ports: ["8080:80"]
    volumes:
      - ./frontend/index.html:/usr/share/nginx/html/index.html:ro
    depends_on: [backend]
volumes:
  dbdata: {}
